/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package master;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author IBRAR
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        setSize(1440, 1031);
        setResizable(false);
        setLocationRelativeTo(null);
        
        initComponents();
         
         timenow();
         tot_buku();
         tot_siswa();
         tot_transaksi();
    }

     private void timenow() {
    // ActionListener untuk Keperluan Timer
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                // Membuat Date
                java.util.Date dt = new java.util.Date();
                // Membuat date format
                java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat ("EEEE, dd MMMMM yyyy") ;
                // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
                if (nilai_jam <= 9) {
                    // Tambahkan "0" didepannya
                    nol_jam = "0";
                }
                // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
                if (nilai_menit <= 9) {
                    // Tambahkan "0" didepannya
                    nol_menit = "0";
                }
                // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
                if (nilai_detik <= 9) {
                    // Tambahkan "0" didepannya
                    nol_detik = "0";
                }
                // Membuat String JAM, MENIT, DETIK
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                // Menampilkan pada Layar
                timenow.setText(kal.format(dt)+"     "+jam + ":" + menit + ":" + detik+"                                   ");
            }
        };
        // Timer
        new javax.swing.Timer(1000, taskPerformer).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        timenow = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buku = new javax.swing.JPanel();
        banyak_buku = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        transaksi = new javax.swing.JPanel();
        banyak_transaksi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        siswa = new javax.swing.JPanel();
        banyak_siswa = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        laporan = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        headdiv = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1440, 1031));

        body.setPreferredSize(new java.awt.Dimension(100, 170));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(15, 4, 76));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timenow.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        timenow.setForeground(new java.awt.Color(255, 255, 255));
        timenow.setText("now");
        header.add(timenow, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(15, 4, 76));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user icon.png"))); // NOI18N
        jPanel1.add(jLabel18);

        header.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 90, 40));

        body.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1140, 45));

        sidebar.setBackground(new java.awt.Color(15, 4, 76));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/20220330_235930 1.png"))); // NOI18N
        logo.setToolTipText("LOGO LIBRON");
        sidebar.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LIBRARY.png"))); // NOI18N
        sidebar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 130, 570));

        body.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1000));

        buku.setToolTipText("Data Buku");
        buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bukuMouseClicked(evt);
            }
        });
        buku.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        banyak_buku.setFont(new java.awt.Font("Dubai", 1, 100)); // NOI18N
        banyak_buku.setForeground(new java.awt.Color(255, 255, 255));
        banyak_buku.setText("24");
        buku.add(banyak_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(15, 4, 76));
        jLabel5.setText("BUKU");
        buku.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buku.png"))); // NOI18N
        buku.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/atas.png"))); // NOI18N
        buku.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 210));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bawah.png"))); // NOI18N
        buku.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 200, 480, -1));

        body.add(buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 400, 300));

        transaksi.setToolTipText("Data Transaksi");
        transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiMouseClicked(evt);
            }
        });
        transaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        banyak_transaksi.setFont(new java.awt.Font("Dubai", 1, 100)); // NOI18N
        banyak_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        banyak_transaksi.setText("24");
        transaksi.add(banyak_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(15, 4, 76));
        jLabel6.setText("TRANSAKSI");
        transaksi.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo majer 1.png"))); // NOI18N
        transaksi.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/atas.png"))); // NOI18N
        transaksi.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 210));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bawah.png"))); // NOI18N
        transaksi.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 210, 480, -1));

        body.add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, 400, 310));

        siswa.setToolTipText("Data Siswa");
        siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siswaMouseClicked(evt);
            }
        });
        siswa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        banyak_siswa.setFont(new java.awt.Font("Dubai", 1, 100)); // NOI18N
        banyak_siswa.setForeground(new java.awt.Color(255, 255, 255));
        banyak_siswa.setText("24");
        siswa.add(banyak_siswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(15, 4, 76));
        jLabel10.setText("SISWA");
        siswa.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/siswa.png"))); // NOI18N
        siswa.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/atas.png"))); // NOI18N
        siswa.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 210));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bawah.png"))); // NOI18N
        siswa.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 200, 480, -1));

        body.add(siswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 160, 410, 300));

        laporan.setToolTipText("Data Laporan");
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
        });
        laporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(15, 4, 76));
        jLabel14.setText("LAPORAN");
        laporan.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/20220331_122135 1.png"))); // NOI18N
        laporan.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/atas.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        laporan.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 210));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bawah.png"))); // NOI18N
        laporan.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 210, 480, -1));

        body.add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 600, 410, 310));

        headdiv.setBackground(new java.awt.Color(15, 4, 76));
        headdiv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("DASHBOARD");
        headdiv.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        body.add(headdiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 1110, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        body.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 1170, 970));

        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukuMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new buku().setVisible(true);
    }//GEN-LAST:event_bukuMouseClicked

    private void transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new transaksi().setVisible(true);
    }//GEN-LAST:event_transaksiMouseClicked

    private void siswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siswaMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new siswa().setVisible(true);
    }//GEN-LAST:event_siswaMouseClicked

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new laporan().setVisible(true);
    }//GEN-LAST:event_laporanMouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
       this.setVisible(false);
       new laporan().setVisible(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        this.setVisible(true);
        new user(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void tot_buku() {
        try {
            String sql = "SELECT SUM(stok) AS jumlah FROM buku";
            Connection con = new database.connection().configDB();
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            if(rs.next()) {
               banyak_buku.setText(rs.getString("jumlah") + "");
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
    
    private void tot_siswa() {
        try {
            String sql = "SELECT COUNT(*) AS nama FROM siswa";
            Connection con = new database.connection().configDB();
            java.sql.Statement st = con.createStatement();
                java.sql.ResultSet rs = st.executeQuery(sql);
            if(rs.next()) {
               banyak_siswa.setText(rs.getString("nama") + "");
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
    
    private void tot_transaksi() {
        try {
            String sql = "SELECT COUNT(*) AS jumlah FROM Pinjam";
            Connection con = new database.connection().configDB();
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            if(rs.next()) {
               banyak_transaksi.setText(rs.getString("jumlah") + "");
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banyak_buku;
    private javax.swing.JLabel banyak_siswa;
    private javax.swing.JLabel banyak_transaksi;
    private javax.swing.JPanel body;
    private javax.swing.JPanel buku;
    private javax.swing.JPanel headdiv;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel laporan;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel siswa;
    private javax.swing.JLabel timenow;
    private javax.swing.JPanel transaksi;
    // End of variables declaration//GEN-END:variables
}
