/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package master;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import javafx.scene.control.DatePicker;
import javax.swing.JTable;
import javax.swing.table.TableColumn;

/**
 *
 * @author IBRAR
 */
public class laporan extends javax.swing.JFrame {

    DefaultTableModel tbl2 = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    private Object pages;

    /**
     * Creates new form buku
     */
    public laporan() {
        setSize(1440, 1031);
        setResizable(false);
        setLocationRelativeTo(null);
        
      
        
        initComponents();
        timenow();
        tgl_awal.setDateFormatString("yyyy-MM-dd");
        tgl_akhir.setDateFormatString("yyyy-MM-dd");

    }
private DatePicker jDateChooser2;
private DatePicker jDateChooser1;

    private void timenow() {
        // ActionListener untuk Keperluan Timer
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                // Membuat Date
                java.util.Date dt = new java.util.Date();
                // Membuat date format
                java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("EEEE, dd MMMMM yyyy");
                // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
                if (nilai_jam <= 9) {
                    // Tambahkan "0" didepannya
                    nol_jam = "0";
                }
                // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
                if (nilai_menit <= 9) {
                    // Tambahkan "0" didepannya
                    nol_menit = "0";
                }
                // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
                if (nilai_detik <= 9) {
                    // Tambahkan "0" didepannya
                    nol_detik = "0";
                }
                // Membuat String JAM, MENIT, DETIK
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                // Menampilkan pada Layar
                timenow.setText(kal.format(dt) + "     " + jam + ":" + menit + ":" + detik + "                                   ");
            }
        };
        // Timer
        new javax.swing.Timer(1000, taskPerformer).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        timenow = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buku = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        siswa = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        transaksi = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        laporan = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        headdiv = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        print = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_laporan = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tgl_awal = new com.toedter.calendar.JDateChooser();
        tgl_akhir = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setMinimumSize(new java.awt.Dimension(300, 1080));
        body.setPreferredSize(new java.awt.Dimension(1440, 1031));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(15, 4, 76));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timenow.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        timenow.setForeground(new java.awt.Color(255, 255, 255));
        timenow.setText("now");
        header.add(timenow, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        about.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        about.setForeground(new java.awt.Color(51, 255, 51));
        about.setText("?");
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        header.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 40, 50));

        body.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1150, 45));

        sidebar.setBackground(new java.awt.Color(15, 4, 76));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/20220330_235930 4.png"))); // NOI18N
        sidebar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 150, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LIBRARY1.png"))); // NOI18N
        sidebar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        buku.setBackground(new java.awt.Color(69, 40, 232));
        buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bukuMouseClicked(evt);
            }
        });
        buku.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bukuicn.png"))); // NOI18N
        buku.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BUKU");
        buku.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        sidebar.add(buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 300, 90));

        siswa.setBackground(new java.awt.Color(36, 11, 172));
        siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siswaMouseClicked(evt);
            }
        });
        siswa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/manicn.png"))); // NOI18N
        siswa.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SISWA");
        siswa.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        sidebar.add(siswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 300, 90));

        transaksi.setBackground(new java.awt.Color(69, 40, 232));
        transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiMouseClicked(evt);
            }
        });
        transaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo majer 5.png"))); // NOI18N
        transaksi.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TRANSAKSI");
        transaksi.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        sidebar.add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 300, 90));

        laporan.setBackground(new java.awt.Color(36, 11, 172));
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
        });
        laporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/laporan.png"))); // NOI18N
        laporan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("LAPORAN");
        laporan.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        sidebar.add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 300, 90));

        logout.setBackground(new java.awt.Color(202, 0, 0));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo home.png"))); // NOI18N
        jLabel11.setText("   ");
        logout.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 80));

        sidebar.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 790, 120, 100));

        body.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 1030));

        headdiv.setBackground(new java.awt.Color(15, 4, 76));
        headdiv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("LAPORAN");
        headdiv.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        body.add(headdiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 1110, 40));

        jLabel13.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel13.setText("Keterangan");
        body.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 130, -1, -1));

        print.setBackground(new java.awt.Color(15, 4, 76));
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });
        print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("PRINT");
        print.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        body.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 830, 180, 60));

        tb_laporan.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tb_laporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Table Information"
            }
        ));
        jScrollPane1.setViewportView(tb_laporan);

        body.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 1070, 530));

        jLabel14.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel14.setText("Masukkan Tanggal Awal");
        body.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        status.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-", "Dipinjam", "Dikembalikan" }));
        status.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                statusItemStateChanged(evt);
            }
        });
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        body.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 170, 230, 45));

        jLabel17.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel17.setText("Masukkan Tanggal Akhir");
        body.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("\"TRANSAKSI ANDA MENENTUKAN MASA DEPAN ANDA !!!\"");
        body.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 780, -1, -1));

        tgl_awal.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        body.add(tgl_awal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 270, 45));

        tgl_akhir.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        body.add(tgl_akhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 270, 45));

        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new laporan().setVisible(true);
    }//GEN-LAST:event_laporanMouseClicked

    private void transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new transaksi().setVisible(true);
    }//GEN-LAST:event_transaksiMouseClicked

    private void siswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siswaMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new siswa().setVisible(true);
    }//GEN-LAST:event_siswaMouseClicked

    private void bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukuMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new buku().setVisible(true);
    }//GEN-LAST:event_bukuMouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        // TODO add your handling code here:
        new pages.about(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_aboutMouseClicked

    private void statusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_statusItemStateChanged
        // TODO add your handling code here:
        int option = status.getSelectedIndex();
        switch (option){
        case 0: 
            break;
        case 1:
            Object []baris = {"ID", "NIS", "Nama", "Code", "Kode Buku", "Judul Buku", "Jenis Buku", "Tanggal Pinjam", "Tanggal Kembali"};
        tbl2 = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tb_laporan.setModel(tbl2);
        tampil_pinjam();
        lebarKolom();
            break;
        case 2:
        tb_laporan.setModel(tbl2);
        tampil_kembali();
        lebarKolomkbl();
        break;
        default:
            System.out.println("DATA YANG ANDA MASUKKAN SALAH");
    }
        
    }//GEN-LAST:event_statusItemStateChanged

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("DATA TRANSAKSI");
        MessageFormat footer = new MessageFormat("");
        try{
            tb_laporan.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_printMouseClicked

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed
 
    private void tampil_pinjam() {
        Object []baris = {"ID", "NIS", "Nama", "Code", "Kode Buku", "Judul Buku", "Jenis Buku", "Tanggal Pinjam", "Tanggal Kembali"};
        tbl2 = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tb_laporan.setModel(tbl2);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT siswa.*, buku.*, pinjam.* FROM siswa, buku, pinjam WHERE siswa.id_siswa = pinjam.id_siswa AND buku.id_buku = pinjam.id_buku AND pinjam.tgl_pinjam BETWEEN '" + sdf.format(tgl_awal.getDate()) + "' AND '" + sdf.format(tgl_akhir.getDate()) + "' ORDER BY pinjam.tgl_pinjam ASC";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            
            while (hasil.next()) {
                String idpinjam = hasil.getString("pinjam.id_pinjam");
                String nis = hasil.getString("siswa.nis");
                String nama = hasil.getString("siswa.nama");
                String code = hasil.getString("siswa.kode");
                String kode = hasil.getString("buku.kode");
                String judul = hasil.getString("buku.judul");
                String jenis = hasil.getString("buku.jenis");
                String tanggal_pnjm = hasil.getString("pinjam.tgl_pinjam");
                String tanggal_kmbl = hasil.getString("pinjam.tgl_kembali");
                
                String[] data = {idpinjam, nis, nama, code, kode, judul, jenis, tanggal_pnjm, tanggal_kmbl};
                tbl2.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan DATA!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
            dispose();
        }
    }
   
 private void tampil_kembali() {
        Object []baris = {"ID", "NIS", "Nama", "Kode Buku", "Judul Buku", "Jenis Buku", "Tanggal Pinjam", "Tanggal Kembali", "Stok", "Denda"};
        tbl2 = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tb_laporan.setModel(tbl2);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT siswa.*, buku.*, kembali.* FROM siswa, buku, kembali WHERE siswa.id_siswa = kembali.id_siswa AND buku.id_buku = kembali.id_buku AND kembali.tgl_kembali BETWEEN '" + sdf.format(tgl_awal.getDate()) + "' AND '" + sdf.format(tgl_awal.getDate()) + "' ORDER BY kembali.tgl_kembali ASC";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            
            while (hasil.next()) {
                String idpinjam = hasil.getString("kembali.id_kembali");
                String nis = hasil.getString("siswa.nis");
                String nama = hasil.getString("siswa.nama");
                String kode = hasil.getString("buku.kode");
                String judul = hasil.getString("buku.judul");
                String jenis = hasil.getString("buku.jenis");
                String tanggal_pnjm = hasil.getString("kembali.tgl_pinjam");
                String tanggal_kmbl = hasil.getString("kembali.tgl_kembali");
                String stok = hasil.getString("kembali.stok");
                String denda = hasil.getString("kembali.denda");
              
                String[] data = {idpinjam, nis, nama, kode, judul, jenis, tanggal_pnjm, tanggal_kmbl, stok, denda};
                tbl2.addRow(data);
            }
        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Gagal Menampilkan DATA!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
            System.exit(0);
            dispose();
        }
    }
 
 
    public void lebarKolom(){ 
        TableColumn column;
        tb_laporan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tb_laporan.getColumnModel().getColumn(0); 
        column.setPreferredWidth(50);
        column = tb_laporan.getColumnModel().getColumn(1); 
        column.setPreferredWidth(70); 
        column = tb_laporan.getColumnModel().getColumn(2); 
        column.setPreferredWidth(220); 
        column = tb_laporan.getColumnModel().getColumn(3); 
        column.setPreferredWidth(100);
        column = tb_laporan.getColumnModel().getColumn(4); 
        column.setPreferredWidth(70);
        column = tb_laporan.getColumnModel().getColumn(5); 
        column.setPreferredWidth(184);
        column = tb_laporan.getColumnModel().getColumn(6); 
        column.setPreferredWidth(130);
        column = tb_laporan.getColumnModel().getColumn(7); 
        column.setPreferredWidth(120);
        column = tb_laporan.getColumnModel().getColumn(8); 
        column.setPreferredWidth(120);
    }
    
    public void lebarKolomkbl(){ 
        TableColumn column;
        tb_laporan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tb_laporan.getColumnModel().getColumn(0); 
        column.setPreferredWidth(50);
        column = tb_laporan.getColumnModel().getColumn(1); 
        column.setPreferredWidth(70); 
        column = tb_laporan.getColumnModel().getColumn(2); 
        column.setPreferredWidth(220); 
        column = tb_laporan.getColumnModel().getColumn(3); 
        column.setPreferredWidth(80);
        column = tb_laporan.getColumnModel().getColumn(4); 
        column.setPreferredWidth(184);
        column = tb_laporan.getColumnModel().getColumn(5); 
        column.setPreferredWidth(130);
        column = tb_laporan.getColumnModel().getColumn(6); 
        column.setPreferredWidth(100);
        column = tb_laporan.getColumnModel().getColumn(7); 
        column.setPreferredWidth(120);
        column = tb_laporan.getColumnModel().getColumn(8); 
        column.setPreferredWidth(50);
        column = tb_laporan.getColumnModel().getColumn(9); 
        column.setPreferredWidth(60);
    }
 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JPanel body;
    private javax.swing.JPanel buku;
    private javax.swing.JPanel headdiv;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel laporan;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel print;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel siswa;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTable tb_laporan;
    private com.toedter.calendar.JDateChooser tgl_akhir;
    private com.toedter.calendar.JDateChooser tgl_awal;
    private javax.swing.JLabel timenow;
    private javax.swing.JPanel transaksi;
    // End of variables declaration//GEN-END:variables
}
