/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package master;

import pages.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Frame;
import javax.swing.table.TableColumn;

/**
 *
 * @author IBRAR
 */
public class siswa extends javax.swing.JFrame {

    DefaultTableModel tbl2 = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    private Object pages;

    /**
     * Creates new form buku
     */
    public siswa() {
        setSize(1440, 1031);
        setResizable(false);
        setLocationRelativeTo(null);
        
        initComponents();

        timenow();
        tampil_siswa();
        lebarKolom();
    }

    private void timenow() {
        // ActionListener untuk Keperluan Timer
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                // Membuat Date
                java.util.Date dt = new java.util.Date();
                // Membuat date format
                java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("EEEE, dd MMMMM yyyy");
                // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
                if (nilai_jam <= 9) {
                    // Tambahkan "0" didepannya
                    nol_jam = "0";
                }
                // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
                if (nilai_menit <= 9) {
                    // Tambahkan "0" didepannya
                    nol_menit = "0";
                }
                // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
                if (nilai_detik <= 9) {
                    // Tambahkan "0" didepannya
                    nol_detik = "0";
                }
                // Membuat String JAM, MENIT, DETIK
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                // Menampilkan pada Layar
                timenow.setText(kal.format(dt) + "     " + jam + ":" + menit + ":" + detik + "                                   ");
            }
        };
        // Timer
        new javax.swing.Timer(1000, taskPerformer).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        timenow = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buku = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        siswa = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        transaksi = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        laporan = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        headdiv = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_siswa = new javax.swing.JTable();
        search_siswa = new placeholder.search();
        result_siswa = new javax.swing.JLabel();
        fitur = new javax.swing.JPanel();
        add = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        refresh = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setMinimumSize(new java.awt.Dimension(300, 1080));
        body.setPreferredSize(new java.awt.Dimension(1440, 1031));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(15, 4, 76));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timenow.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        timenow.setForeground(new java.awt.Color(255, 255, 255));
        timenow.setText("now");
        header.add(timenow, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        about.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        about.setForeground(new java.awt.Color(51, 255, 51));
        about.setText("?");
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        header.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 40, 50));

        body.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1160, 45));

        sidebar.setBackground(new java.awt.Color(15, 4, 76));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/20220330_235930 4.png"))); // NOI18N
        sidebar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 150, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LIBRARY1.png"))); // NOI18N
        sidebar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        buku.setBackground(new java.awt.Color(69, 40, 232));
        buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bukuMouseClicked(evt);
            }
        });
        buku.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bukuicn.png"))); // NOI18N
        buku.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BUKU");
        buku.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        sidebar.add(buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 300, 90));

        siswa.setBackground(new java.awt.Color(36, 11, 172));
        siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siswaMouseClicked(evt);
            }
        });
        siswa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/manicn.png"))); // NOI18N
        siswa.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SISWA");
        siswa.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        sidebar.add(siswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 300, 90));

        transaksi.setBackground(new java.awt.Color(69, 40, 232));
        transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiMouseClicked(evt);
            }
        });
        transaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo majer 5.png"))); // NOI18N
        transaksi.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TRANSAKSI");
        transaksi.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        sidebar.add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 300, 90));

        laporan.setBackground(new java.awt.Color(36, 11, 172));
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
        });
        laporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/laporan.png"))); // NOI18N
        laporan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("LAPORAN");
        laporan.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        sidebar.add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 300, 90));

        logout.setBackground(new java.awt.Color(202, 0, 0));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo home.png"))); // NOI18N
        logout.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 80));

        sidebar.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 790, 120, 100));

        body.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 1030));

        headdiv.setBackground(new java.awt.Color(15, 4, 76));
        headdiv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SISWA");
        headdiv.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        body.add(headdiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 1110, 40));

        tb_siswa.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tb_siswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Jurusan", "Tempat Lahir", "Tanggal Lahir", "Tanggal Masuk", "Code"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tb_siswa);

        body.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 1080, 410));

        search_siswa.setToolTipText("Cari Data");
        search_siswa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        search_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_siswaActionPerformed(evt);
            }
        });
        search_siswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_siswaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_siswaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_siswaKeyTyped(evt);
            }
        });
        body.add(search_siswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 140, 270, 40));

        result_siswa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        result_siswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        body.add(result_siswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 750, 40));

        fitur.setBackground(new java.awt.Color(255, 255, 255));
        fitur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fitur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(74, 176, 12));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ADD1 6.png"))); // NOI18N
        add.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 70, 50));

        jLabel14.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ADD");
        add.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 30));

        fitur.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 180, 70));

        edit.setBackground(new java.awt.Color(234, 183, 4));
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/EDIT1 10.png"))); // NOI18N
        edit.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 90, 60));

        jLabel16.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("EDIT");
        edit.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 30));

        fitur.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 180, 70));

        delete.setBackground(new java.awt.Color(245, 0, 0));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sampah1 10.png"))); // NOI18N
        delete.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        jLabel18.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("DELETE");
        delete.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 30));

        fitur.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 180, 70));

        refresh.setBackground(new java.awt.Color(15, 4, 76));
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });
        refresh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        refresh.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 60));

        jLabel20.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("REFRESH");
        refresh.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        fitur.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 180, 70));

        body.add(fitur, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 820, 1080, 120));
        body.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        body.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 1180, 1000));

        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_siswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_siswaActionPerformed

    private void search_siswaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_siswaKeyPressed
//         TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            search_siswa();
        }
    }//GEN-LAST:event_search_siswaKeyPressed

    private void search_siswaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_siswaKeyTyped
        // TODO add your handling code here:
        search_siswa();
    }//GEN-LAST:event_search_siswaKeyTyped

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        // TODO add your handling code here:
        search_siswa.setText("");
        result_siswa.setText("");
        tampil_siswa();
        lebarKolom();
    }//GEN-LAST:event_refreshMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
        int baris = tb_siswa.getSelectedRow();
        if (baris >= 0) {
            String id = tbl2.getValueAt(baris, 0).toString();
            String nis =tbl2.getValueAt(baris, 1).toString();
            String nama = tbl2.getValueAt(baris, 2).toString();

            
            int x = JOptionPane.showConfirmDialog(null, "Data Siswa dengan\n\nJudul: " + nama + "\nNIS: " + nis + "\n\nakan Anda hapus, yakin?\nData peminjaman dengan Siswa ini juga akan ikut terhapus!", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (x == JOptionPane.YES_OPTION) {
                try {
                    Connection con = new database.connection().configDB();
                    String sql = "DELETE FROM siswa WHERE id_siswa = '" + id + "'";
                    java.sql.Statement st = con.createStatement();
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    tampil_siswa();
                    lebarKolom();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Gagal menghapus data!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Anda belum memilih data yang akan dihapus!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        // TODO add your handling code here:
        int baris = tb_siswa.getSelectedRow();
        if (baris >= 0) {
            String nis = tbl2.getValueAt(baris, 0).toString();
            try {
                Connection con = new database.connection().configDB();
                String sql = "SELECT * FROM siswa WHERE id_siswa = '" + nis + "'";
                java.sql.Statement st = con.createStatement();
                java.sql.ResultSet rs = st.executeQuery(sql);

                if (rs.next()) {
                    String id = rs.getString("id_siswa");
                    Frame frame = new Frame();
                    new pages.edit_siswa(frame, rootPaneCheckingEnabled, id).setVisible(true);
                }
                tampil_siswa();
                lebarKolom();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal menyeleksi data!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Anda belum memilih data yang akan diubah!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_editMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        this.setVisible(true);
        new add_siswa().setVisible(true);
        tampil_siswa();
        lebarKolom();
    }//GEN-LAST:event_addMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new laporan().setVisible(true);
    }//GEN-LAST:event_laporanMouseClicked

    private void transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new transaksi().setVisible(true);
    }//GEN-LAST:event_transaksiMouseClicked

    private void siswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siswaMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new siswa().setVisible(true);
    }//GEN-LAST:event_siswaMouseClicked

    private void bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukuMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new buku().setVisible(true);
    }//GEN-LAST:event_bukuMouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        // TODO add your handling code here:
        new pages.about(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_aboutMouseClicked

    private void search_siswaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_siswaKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_search_siswaKeyReleased

    private void tampil_siswa() {
        Object[] baris = {"ID", "NIS", "Nama", "Jurusan", "Tempat lahir", "Tanggal Lahir", "Tanggal Masuk", "Code"};
        tbl2 = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tb_siswa.setModel(tbl2);
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT * FROM siswa ";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);

            while (hasil.next()) {

                String id = hasil.getString("id_siswa");
                String nis = hasil.getString("nis");
                String nama = hasil.getString("nama");
                String jurusan = hasil.getString("jurusan");
                String tl = hasil.getString("tempat_lahir");
                String ttl = hasil.getString("tanggal_lahir");
                String masuk = hasil.getString("tgl_masuk");
                String code = hasil.getString("kode");
               


                String[] data = {id, nis, nama, jurusan, tl, ttl, masuk, code};
                tbl2.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan DATA!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
            dispose();
        }
    }

private void search_siswa() {
        String query = search_siswa.getText();
        
       Object[] baris = {"ID", "NIS", "Nama", "Jurusan", "Tempat lahir", "Tanggal Lahir", "Tanggal Masuk","Code"};
        tbl2 = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tb_siswa.setModel(tbl2);
        
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT * FROM siswa WHERE CONCAT(id_siswa, nis, nama, jurusan, tempat_lahir, tanggal_lahir, tgl_masuk, kode) LIKE '%"+query+"%'";
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet hasil = stmt.executeQuery(sql);
            
            while (hasil.next()) {
                String id = hasil.getString("id_siswa");
               String nis = hasil.getString("nis");
                String nama = hasil.getString("nama");
                String jurusan = hasil.getString("jurusan");
                String tl = hasil.getString("tempat_lahir");
                String ttl = hasil.getString("tanggal_lahir");
                String masuk = hasil.getString("tgl_masuk");
                String code = hasil.getString("kode");
                
           
                String[] data = {id, nis, nama, jurusan, tl, ttl, masuk, code};
                tbl2.addRow(data);
                lebarKolom();
            }
            
            if (!query.equals("")) {
                result_siswa.setText("Hasil pencarian dari: '"+query+"'");
            } else {
                result_siswa.setText("");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

public void lebarKolom(){ 
        TableColumn column;
        tb_siswa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tb_siswa.getColumnModel().getColumn(0); 
        column.setPreferredWidth(50);
        column = tb_siswa.getColumnModel().getColumn(1); 
        column.setPreferredWidth(70); 
        column = tb_siswa.getColumnModel().getColumn(2); 
        column.setPreferredWidth(200); 
        column = tb_siswa.getColumnModel().getColumn(3); 
        column.setPreferredWidth(220);
        column = tb_siswa.getColumnModel().getColumn(4); 
        column.setPreferredWidth(150);
        column = tb_siswa.getColumnModel().getColumn(5); 
        column.setPreferredWidth(130);
        column = tb_siswa.getColumnModel().getColumn(6); 
        column.setPreferredWidth(130);
        column = tb_siswa.getColumnModel().getColumn(7); 
        column.setPreferredWidth(124);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JPanel add;
    private javax.swing.JPanel body;
    private javax.swing.JPanel buku;
    private javax.swing.JPanel delete;
    private javax.swing.JPanel edit;
    private javax.swing.JPanel fitur;
    private javax.swing.JPanel headdiv;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel laporan;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel refresh;
    private javax.swing.JLabel result_siswa;
    private javax.swing.JTextField search_siswa;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel siswa;
    private javax.swing.JTable tb_siswa;
    private javax.swing.JLabel timenow;
    private javax.swing.JPanel transaksi;
    // End of variables declaration//GEN-END:variables
}
