/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package master;

import database.connection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Frame;
import javax.swing.table.TableColumn;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/**
 *
 * @author IBRAR
 */
public class transaksi extends javax.swing.JFrame {

    DefaultTableModel tbl2 = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    private Object pages;

    /**
     * Creates new form buku
     */
    public transaksi() {
        setSize(1440, 1031);
        setResizable(false);
        setLocationRelativeTo(null);
        
        initComponents();
        
        timenow();
        tampil_peminjaman();
        lebarKolom();
        
      
    }

    private void timenow() {
        // ActionListener untuk Keperluan Timer
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                // Membuat Date
                java.util.Date dt = new java.util.Date();
                // Membuat date format
                java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("EEEE, dd MMMMM yyyy");
                // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
                if (nilai_jam <= 9) {
                    // Tambahkan "0" didepannya
                    nol_jam = "0";
                }
                // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
                if (nilai_menit <= 9) {
                    // Tambahkan "0" didepannya
                    nol_menit = "0";
                }
                // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
                if (nilai_detik <= 9) {
                    // Tambahkan "0" didepannya
                    nol_detik = "0";
                }
                // Membuat String JAM, MENIT, DETIK
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                // Menampilkan pada Layar
                timenow.setText(kal.format(dt) + "     " + jam + ":" + menit + ":" + detik + "                                   ");
            }
        };
        // Timer
        new javax.swing.Timer(1000, taskPerformer).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        timenow = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buku = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        siswa = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        transaksi = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        laporan = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        headdiv = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        fitur = new javax.swing.JPanel();
        add = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        kembali = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        refresh = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_transaksi = new javax.swing.JTable();
        result_siswa = new javax.swing.JLabel();
        search_transaksi = new placeholder.search();
        datakembali = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        tampil = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setMinimumSize(new java.awt.Dimension(300, 1080));
        body.setPreferredSize(new java.awt.Dimension(1440, 1031));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(15, 4, 76));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timenow.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        timenow.setForeground(new java.awt.Color(255, 255, 255));
        timenow.setText("now");
        header.add(timenow, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        about.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        about.setForeground(new java.awt.Color(51, 255, 51));
        about.setText("?");
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        header.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 40, 50));

        body.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1150, 45));

        sidebar.setBackground(new java.awt.Color(15, 4, 76));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/20220330_235930 4.png"))); // NOI18N
        sidebar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 150, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LIBRARY1.png"))); // NOI18N
        sidebar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        buku.setBackground(new java.awt.Color(69, 40, 232));
        buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bukuMouseClicked(evt);
            }
        });
        buku.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bukuicn.png"))); // NOI18N
        buku.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BUKU");
        buku.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        sidebar.add(buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 300, 90));

        siswa.setBackground(new java.awt.Color(36, 11, 172));
        siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siswaMouseClicked(evt);
            }
        });
        siswa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/manicn.png"))); // NOI18N
        siswa.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SISWA");
        siswa.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        sidebar.add(siswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 300, 90));

        transaksi.setBackground(new java.awt.Color(69, 40, 232));
        transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiMouseClicked(evt);
            }
        });
        transaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo majer 5.png"))); // NOI18N
        transaksi.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TRANSAKSI");
        transaksi.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        sidebar.add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 300, 90));

        laporan.setBackground(new java.awt.Color(36, 11, 172));
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
        });
        laporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/laporan.png"))); // NOI18N
        laporan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("LAPORAN");
        laporan.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        sidebar.add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 300, 90));

        logout.setBackground(new java.awt.Color(202, 0, 0));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo home.png"))); // NOI18N
        logout.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 80));

        sidebar.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 790, 120, 100));

        body.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 1030));

        headdiv.setBackground(new java.awt.Color(15, 4, 76));
        headdiv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TRANSAKSI");
        headdiv.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        body.add(headdiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 1110, 40));

        fitur.setBackground(new java.awt.Color(255, 255, 255));
        fitur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fitur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(74, 176, 12));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ADD1 6.png"))); // NOI18N
        add.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 70, 50));

        jLabel14.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ADD");
        add.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 30));

        fitur.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 180, 70));

        edit.setBackground(new java.awt.Color(234, 183, 4));
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/EDIT1 10.png"))); // NOI18N
        edit.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 90, 60));

        jLabel16.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("EDIT");
        edit.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 30));

        fitur.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 180, 70));

        kembali.setBackground(new java.awt.Color(245, 0, 0));
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        kembali.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("RETURN");
        kembali.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 30));

        fitur.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 180, 70));

        refresh.setBackground(new java.awt.Color(15, 4, 76));
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });
        refresh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        refresh.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 60));

        jLabel20.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("REFRESH");
        refresh.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        fitur.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 180, 70));

        body.add(fitur, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 820, 1080, 120));

        tb_transaksi.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tb_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Jurusan", "Tempat Lahir", "Tanggal Lahir", "Tanggal Masuk"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tb_transaksi);

        body.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 1080, 440));

        result_siswa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        result_siswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        body.add(result_siswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 750, 40));

        search_transaksi.setToolTipText("Cari Data");
        search_transaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        search_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_transaksiActionPerformed(evt);
            }
        });
        search_transaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_transaksiKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_transaksiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_transaksiKeyTyped(evt);
            }
        });
        body.add(search_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 140, 260, 40));

        datakembali.setBackground(new java.awt.Color(15, 4, 76));
        datakembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datakembaliMouseClicked(evt);
            }
        });
        datakembali.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("          DATA KEMBALI");
        datakembali.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 270, -1));

        body.add(datakembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 740, 270, 60));

        tampil.setBackground(new java.awt.Color(15, 4, 76));
        tampil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tampilMouseClicked(evt);
            }
        });
        tampil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("DIAGRAM LINE CHART");
        tampil.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 60));

        body.add(tampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 740, 270, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        body.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 1160, 1000));

        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_transaksiActionPerformed

    private void search_transaksiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_transaksiKeyPressed
//         TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            search_transaksi();
        }
    }//GEN-LAST:event_search_transaksiKeyPressed

    private void search_transaksiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_transaksiKeyTyped
        // TODO add your handling code here:
        search_transaksi();
    }//GEN-LAST:event_search_transaksiKeyTyped

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        // TODO add your handling code here:
        search_transaksi.setText("");
        result_siswa.setText("");
        tampil_peminjaman();
        lebarKolom();
    }//GEN-LAST:event_refreshMouseClicked

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
        // TODO add your handling code here:
        int baris = tb_transaksi.getSelectedRow();
        if (baris >= 0) {
            String idpinjam = tbl2.getValueAt(baris, 0).toString();
            System.out.println(idpinjam);
            
            try {
                Connection con = new database.connection().configDB();
                String sql = "SELECT siswa.*, buku.*, pinjam.* FROM siswa, buku, pinjam WHERE pinjam.id_pinjam = '"+idpinjam+"' ";
                java.sql.Statement stat = con.createStatement();
                java.sql.ResultSet rs = stat.executeQuery(sql);
                
                if (rs.next()) {
                    String id = rs.getString("id_pinjam");
                    System.out.println(id);
                    Frame frame = new Frame();
                    new pages.transaksi_kembali(frame, rootPaneCheckingEnabled, id).setVisible(true);
                }
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal menyeleksi data!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Anda belum memilih data yang akan diubah!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        lebarKolom();
    }//GEN-LAST:event_kembaliMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        // TODO add your handling code here:
        int baris = tb_transaksi.getSelectedRow();
        if (baris >= 0) {
            String idpinjam = tbl2.getValueAt(baris, 0).toString();
            System.out.println(idpinjam);
            
            try {
                Connection con = new database.connection().configDB();
                String sql = "SELECT siswa.*, buku.*, pinjam.* FROM siswa, buku, pinjam WHERE pinjam.id_pinjam = '"+idpinjam+"' ";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet rs = stat.executeQuery(sql);
                
                if (rs.next()) {
                    String id = rs.getString("id_pinjam");
                    System.out.println(id);
                    Frame frame = new Frame();
                    new pages.edit_transaksi(frame, rootPaneCheckingEnabled, id).setVisible(true);
                }
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal menyeleksi data!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Anda belum memilih data yang akan diubah!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        lebarKolom();
    }//GEN-LAST:event_editMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        new pages.add_transaksi(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_addMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new laporan().setVisible(true);
    }//GEN-LAST:event_laporanMouseClicked

    private void transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new transaksi().setVisible(true);
    }//GEN-LAST:event_transaksiMouseClicked

    private void siswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siswaMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new siswa().setVisible(true);
    }//GEN-LAST:event_siswaMouseClicked

    private void bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukuMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new buku().setVisible(true);
    }//GEN-LAST:event_bukuMouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        // TODO add your handling code here:
        new pages.about(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_aboutMouseClicked

    private void search_transaksiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_transaksiKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_search_transaksiKeyReleased

    private void datakembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datakembaliMouseClicked
        // TODO add your handling code here:
        this.setVisible(true);
        new pages.data_kembali().setVisible(true);
    }//GEN-LAST:event_datakembaliMouseClicked

    private void tampilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tampilMouseClicked
        // TODO add your handling code here:
        try {
            String query = "SELECT tgl_pinjam, SUM(stok) AS Jumlah_Buku FROM pinjam GROUP BY tgl_pinjam ORDER BY tgl_pinjam ASC";
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(connection.mysqlconfig,query);
            JFreeChart chart = ChartFactory.createLineChart("Line Chart Diagram Transaksi", "Tanggal Pinjam", "Buku Dipinjam", dataset, PlotOrientation.VERTICAL, true, true, false);
            BarRenderer renderer = null;
            CategoryPlot plot = null;
            renderer = new BarRenderer();
            ChartFrame frame = new ChartFrame("query chart", chart);
            frame.setVisible(true);
            frame.setSize(1000, 1000);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tampilMouseClicked

    
     private void tampil_peminjaman() {
        Object []baris = {"ID", "NIS", "Nama", "jurusan", "Kode Buku", "Judul Buku", "Jenis Buku", "Tanggal Pinjam", "Tanggal Kembali"};
        tbl2 = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tb_transaksi.setModel(tbl2);
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT siswa.*, buku.*, pinjam.* FROM siswa, buku, pinjam WHERE siswa.id_siswa = pinjam.id_siswa AND buku.id_buku = pinjam.id_buku ORDER BY id_pinjam ASC";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            
            while (hasil.next()) {
                String idpinjam = hasil.getString("pinjam.id_pinjam");
                String nis = hasil.getString("siswa.nis");
                String nama = hasil.getString("siswa.nama");
                String code = hasil.getString("siswa.jurusan");
                String kode = hasil.getString("buku.kode");
                String judul = hasil.getString("buku.judul");
                String jenis = hasil.getString("buku.jenis");
                String tanggal_pnjm = hasil.getString("pinjam.tgl_pinjam");
                String tanggal_kmbl = hasil.getString("pinjam.tgl_kembali");
                
                String[] data = {idpinjam, nis, nama, code, kode, judul, jenis, tanggal_pnjm, tanggal_kmbl};
                tbl2.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan DATA!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
            dispose();
        }
    }
    

private void search_transaksi() {
        String query = search_transaksi.getText();
        
       Object []baris = {"ID", "NIS", "Nama", "Code", "Kode Buku", "Judul Buku", "Jenis Buku", "Tanggal Pinjam", "Tanggal Kembali"};
        tbl2 = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tb_transaksi.setModel(tbl2);
        
        try {
            Connection con = new database.connection().configDB();
            String sql ="SELECT * FROM pinjam JOIN buku ON pinjam.id_buku = buku.id_buku JOIN siswa ON siswa.id_siswa = pinjam.id_siswa WHERE CONCAT(id_pinjam, siswa.nis, siswa.nama, siswa.kode, siswa.jurusan, buku.kode, buku.judul, buku.jenis, pinjam.tgl_pinjam, pinjam.tgl_kembali) LIKE '%"+query+"%'";
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet hasil = stmt.executeQuery(sql);
            
            while (hasil.next()) {
                String idpinjam = hasil.getString("pinjam.id_pinjam");
                String nis = hasil.getString("siswa.nis");
                String nama = hasil.getString("siswa.nama");
                String code = hasil.getString("siswa.kode");
                String kode = hasil.getString("buku.kode");
                String judul = hasil.getString("buku.judul");
                String jenis = hasil.getString("buku.jenis");
                String tanggal_pnjm = hasil.getString("pinjam.tgl_pinjam");
                String tanggal_kmbl = hasil.getString("pinjam.tgl_kembali");
             
                String[] data = {idpinjam, nis, nama, code, kode, judul, jenis, tanggal_pnjm, tanggal_kmbl};
                tbl2.addRow(data);
                lebarKolom();
            }
            
            if (!query.equals("")) {
                result_siswa.setText("Hasil pencarian dari: '"+query+"'");
            } else {
                result_siswa.setText("");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

public void lebarKolom(){ 
        TableColumn column;
        tb_transaksi.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tb_transaksi.getColumnModel().getColumn(0); 
        column.setPreferredWidth(50);
        column = tb_transaksi.getColumnModel().getColumn(1); 
        column.setPreferredWidth(70); 
        column = tb_transaksi.getColumnModel().getColumn(2); 
        column.setPreferredWidth(150); 
        column = tb_transaksi.getColumnModel().getColumn(3); 
        column.setPreferredWidth(230);
        column = tb_transaksi.getColumnModel().getColumn(4); 
        column.setPreferredWidth(70);
        column = tb_transaksi.getColumnModel().getColumn(5); 
        column.setPreferredWidth(134);
        column = tb_transaksi.getColumnModel().getColumn(6); 
        column.setPreferredWidth(130);
        column = tb_transaksi.getColumnModel().getColumn(7); 
        column.setPreferredWidth(120);
        column = tb_transaksi.getColumnModel().getColumn(8); 
        column.setPreferredWidth(120);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JPanel add;
    private javax.swing.JPanel body;
    private javax.swing.JPanel buku;
    private javax.swing.JPanel datakembali;
    private javax.swing.JPanel edit;
    private javax.swing.JPanel fitur;
    private javax.swing.JPanel headdiv;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel kembali;
    private javax.swing.JPanel laporan;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel refresh;
    private javax.swing.JLabel result_siswa;
    private javax.swing.JTextField search_transaksi;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel siswa;
    private javax.swing.JPanel tampil;
    private javax.swing.JTable tb_transaksi;
    private javax.swing.JLabel timenow;
    private javax.swing.JPanel transaksi;
    // End of variables declaration//GEN-END:variables
}
