package master;


import java.sql.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ibrar
 */
public class user extends javax.swing.JDialog {

    /**
     * Creates new form userinfo
     */
    public user(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        setSize(1000, 760);
        setResizable(false);
        setLocationRelativeTo(null);
        this.setUndecorated(true);
        
        initComponents();
        
        username.setEditable(false);
        password.setEditable(false);
        userlawas.setVisible(false);
        passlawas.setVisible(false);
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        sidebar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        header = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        esbtn = new javax.swing.JPanel();
        edit_save = new javax.swing.JLabel();
        userlawas = new javax.swing.JLabel();
        passlawas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 330, 40));

        sidebar.setBackground(new java.awt.Color(15, 4, 76));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LIBRARY.png"))); // NOI18N
        sidebar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 130, 570));

        jPanel1.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 790));

        jLabel1.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel1.setText("Nama Pengguna");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        password.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 330, 40));

        header.setBackground(new java.awt.Color(15, 4, 76));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        close.setForeground(new java.awt.Color(255, 0, 51));
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        header.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 40, 50));

        jLabel12.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("INFORMASI USER");
        header.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 970, 45));

        jLabel2.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel2.setText("Kata Sandi");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, -1, -1));

        esbtn.setBackground(new java.awt.Color(74, 176, 12));
        esbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                esbtnMouseClicked(evt);
            }
        });

        edit_save.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        edit_save.setForeground(new java.awt.Color(255, 255, 255));
        edit_save.setText("UBAH");

        javax.swing.GroupLayout esbtnLayout = new javax.swing.GroupLayout(esbtn);
        esbtn.setLayout(esbtnLayout);
        esbtnLayout.setHorizontalGroup(
            esbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, esbtnLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(edit_save)
                .addGap(52, 52, 52))
        );
        esbtnLayout.setVerticalGroup(
            esbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(esbtnLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(edit_save)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(esbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, -1, 44));
        jPanel1.add(userlawas, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 111, -1, -1));
        jPanel1.add(passlawas, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 191, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void esbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esbtnMouseClicked
        // TODO add your handling code here:
                if (edit_save.getText().equals("UBAH")) {
            username.setEditable(true);
            password.setEditable(true);
            edit_save.setText("SIMPAN");
        } else if (edit_save.getText().equals("SIMPAN")) {
            String pengguna = userlawas.getText();
            String sandi = passlawas.getText();
            String user = username.getText();
            String pass = password.getText();
            
            try {
                Connection con = new database.connection().configDB();
                String sql = "UPDATE admin SET username = ?, password = ? WHERE username = '"+pengguna+"' AND password = '"+sandi+"'";
                java.sql.PreparedStatement stat = con.prepareStatement(sql);
                stat.setString(1, user);
                stat.setString(2, pass);
                stat.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Username dan Password BERHASIL Diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                
                login n = new login();
                this.setVisible(false);
                n.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Username dan Password GAGAL Diubah", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                
                home n = new home();
                this.setVisible(false);
                n.setVisible(true);
            }
        }
    }//GEN-LAST:event_esbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                user dialog = new user(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void tampil() {
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT * FROM admin";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            
            if (hasil.next()) {
                username.setText(hasil.getString("username"));
                password.setText(hasil.getString("password"));
                userlawas.setText(hasil.getString("username"));
                passlawas.setText(hasil.getString("password"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan DATA!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
            dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JLabel edit_save;
    private javax.swing.JPanel esbtn;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel passlawas;
    private javax.swing.JTextField password;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel userlawas;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
