/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pages;

import java.awt.Point;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author IBRAR
 */
public class add_buku extends javax.swing.JFrame {

    private static Point point = new Point();
    
    private char[] chars = "1234567890".toCharArray();
    private StringBuilder stringBuilder = new StringBuilder();
    private Random random = new Random();
    private String output;
    
    /**
     * Creates new form add_buku
     */
    public add_buku() {
        setSize(1200, 550);
        setResizable(false);
        setLocationRelativeTo(null);
        this.setUndecorated(true);
        
        initComponents();
        thisdate();
        
        kd_buku.setEnabled(false);
    }

    String cmb_id;
    String id_buku;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        simpan = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        id_pengarang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        judul_buku = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        id_penerbit = new javax.swing.JTextField();
        kd_buku = new javax.swing.JTextField();
        stock = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jenis_buku = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tanggal_terbit = new javax.swing.JTextField();
        no_rak = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        body.setPreferredSize(new java.awt.Dimension(1153, 845));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(15, 4, 76));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        close.setForeground(new java.awt.Color(255, 0, 51));
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        header.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 40, 50));

        jLabel12.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ADD BUKU");
        header.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        body.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1350, 45));

        sidebar.setBackground(new java.awt.Color(15, 4, 76));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/20220330_235930 1.png"))); // NOI18N
        sidebar.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        body.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 600));

        simpan.setBackground(new java.awt.Color(74, 176, 12));
        simpan.setForeground(new java.awt.Color(240, 240, 240));
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });
        simpan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/simpan.png"))); // NOI18N
        simpan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SIMPAN");
        simpan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        body.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 210, 60));

        id_pengarang.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        id_pengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_pengarangActionPerformed(evt);
            }
        });
        body.add(id_pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 330, 40));

        jLabel2.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel2.setText("Judul Buku");
        body.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel4.setText("Pengarang");
        body.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel7.setText("Tanggal Terbit");
        body.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, -1, -1));

        judul_buku.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        body.add(judul_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 330, 40));

        jLabel10.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel10.setText("Jenis Buku");
        body.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        id_penerbit.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        body.add(id_penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 330, 40));

        kd_buku.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        body.add(kd_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 330, 40));

        stock.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        body.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 330, 40));

        jLabel3.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel3.setText("Stok");
        body.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel5.setText("Kode Buku");
        body.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jenis_buku.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jenis_buku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ensiklopedia", "Novel", "Komik", "Biografi", "Dongeng", "Karya Ilmiah" }));
        jenis_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenis_bukuActionPerformed(evt);
            }
        });
        body.add(jenis_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 330, 40));

        jLabel11.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel11.setText("Rak");
        body.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("?");
        jLabel1.setToolTipText("KODE akan terisi otomatis");
        body.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, 30));

        jLabel6.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel6.setText("Penerbit");
        body.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, -1, -1));

        tanggal_terbit.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        tanggal_terbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggal_terbitActionPerformed(evt);
            }
        });
        body.add(tanggal_terbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 330, 40));

        no_rak.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        body.add(no_rak, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 330, 40));

        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void tanggal_terbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggal_terbitActionPerformed
        // TODO add your handling code here:

        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd") ;
        tanggal_terbit.setText(""+kal.format(sekarang));

    }//GEN-LAST:event_tanggal_terbitActionPerformed

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked

        String getkode, getjenis, getjudul, gettanggal, getpengarang, getpenerbit, getstok, getrak;

        getkode = kd_buku.getText();
        getjenis = (String)jenis_buku.getSelectedItem();
        getjudul = judul_buku.getText();
        gettanggal = tanggal_terbit.getText();
        getpengarang = id_pengarang.getText();
        getpenerbit = id_penerbit.getText();
        getstok = stock.getText();
        getrak = no_rak.getText();

        if (empty(getjudul) || empty(gettanggal) || empty(getpengarang) || empty(getpenerbit) || empty(getstok) || empty(getrak)) {
            JOptionPane.showMessageDialog(null, "Data yang Anda masukkan belum lengkap!", "Peringatan!", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Connection con = new database.connection().configDB();
                String get = "SELECT * FROM buku WHERE judul = '"+getjudul+"'";
                java.sql.Statement st = con.createStatement();
                java.sql.ResultSet hasil = st.executeQuery(get);

                if (hasil.next()) {
                    JOptionPane.showMessageDialog(null, "Judul buku tidak boleh ada yang sama.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                } else {
                    try {
                        String sql = "INSERT INTO buku VALUES (null, ?, ?, ?, ?, ?, ?, ?, ?)";
                        java.sql.PreparedStatement stat = (PreparedStatement)con.prepareStatement(sql);
                        stat.setString(1, getkode);
                        stat.setString(2, getjenis);
                        stat.setString(3, getjudul);
                        stat.setString(4, gettanggal);
                        stat.setString(5, getpengarang);
                        stat.setString(6, getpenerbit);
                        stat.setString(7, getstok);
                        stat.setString(8, getrak);
                        stat.executeUpdate();
                        
                        this.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Data Buku Berhasil Ditambahkan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Data Buku Gagal Disimpan", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (Exception e) {}
        }
    }//GEN-LAST:event_simpanMouseClicked

    private void id_pengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_pengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_pengarangActionPerformed

    private void jenis_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenis_bukuActionPerformed
        // TODO add your handling code here:
        kode();
    }//GEN-LAST:event_jenis_bukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_buku().setVisible(true);
            }
        });
    }
    
        private String getRandom() {
        for (int length = 0; length < 2; length++) {
            Character character = chars[random.nextInt(chars.length)];
            stringBuilder.append(character);
        }
        output = stringBuilder.toString();
        stringBuilder.delete(0, 6);
        return output;
    }
        
        private void thisdate() {
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd") ;
        tanggal_terbit.setText(""+kal.format(sekarang));
    }
        
        private static boolean empty(final String s) {
        return s == null || s.trim().isEmpty();
    }
    public void kode(){
         cmb_id = (String) jenis_buku.getSelectedItem();
    if ("Ensiklopedia".equals(cmb_id)) {
     id_buku= "ESP"+getRandom();
      } else if ("Novel".equals(cmb_id)) {
     id_buku = "NVL"+getRandom();
      } else if ("Komik".equals(cmb_id)) {
     id_buku = "KMK"+getRandom();
      } else if("Biografi".equals(cmb_id)){
       id_buku = "BGF"+getRandom();
      }else if("Dongeng".equals(cmb_id)){
          id_buku = "DGG"+getRandom();
      } else if("Karya Ilmiah".equals(cmb_id)){
          id_buku = "KIR"+getRandom();
      } 
    kd_buku.setText(id_buku);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JLabel close;
    private javax.swing.JPanel header;
    private javax.swing.JTextField id_penerbit;
    private javax.swing.JTextField id_pengarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jenis_buku;
    private javax.swing.JTextField judul_buku;
    private javax.swing.JTextField kd_buku;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField no_rak;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel simpan;
    private javax.swing.JTextField stock;
    private javax.swing.JTextField tanggal_terbit;
    // End of variables declaration//GEN-END:variables
}
