/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pages;

import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author IBRAR
 */
public class add_transaksi extends javax.swing.JDialog {
    
    
    private static Point point = new Point();
    
    DefaultTableModel tbl1 = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    DefaultTableModel tbl2 = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form add_transaksi
     */
    public add_transaksi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        setSize(1300, 1000);
        setResizable(false);
        setLocationRelativeTo(null);
        this.setUndecorated(true);
        
        
        this.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                point.x = e.getX();
                point.y = e.getY();
            }
        });
        this.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent e) {
                Point p = getLocation();
                setLocation(p.x + e.getX() - point.x, p.y + e.getY() - point.y);
            }
        });
        
        initComponents();
        thisdate();
        
        nis.setEnabled(false);
        nama.setEnabled(false);
        kode_siswa.setEnabled(false);
        kode_buku.setEnabled(false);
        judul.setEnabled(false);
        jenis.setEnabled(false);
        
        id_murid.setVisible(false);
        id_buku.setVisible(false);
        
        tampil_buku();
        tampil_murid();
        lebarKolommrd();
        lebarKolombk();
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_buku = new javax.swing.JTable();
        data_buku = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        kode_buku = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        judul = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tgl_pnjm = new javax.swing.JTextField();
        stok = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tgl_kmbl = new javax.swing.JTextField();
        id_buku = new javax.swing.JTextField();
        data_murid = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nis = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kode_siswa = new javax.swing.JTextField();
        id_murid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_murid = new javax.swing.JTable();
        cari_buku = new placeholder.search_buku();
        cari_murid = new placeholder.search_siswa();
        header = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        simpan = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(15, 4, 76));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/20220330_235930 1.png"))); // NOI18N
        sidebar.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 190, -1, -1));

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 1000));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_buku.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tbl_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Buku", "Judul Buku", "Tanggal Terbit"
            }
        ));
        tbl_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_buku);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 470, 410));

        data_buku.setBackground(new java.awt.Color(255, 255, 255));
        data_buku.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Buku"));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Kode Buku");

        kode_buku.setBackground(new java.awt.Color(204, 204, 204));
        kode_buku.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        kode_buku.setPreferredSize(new java.awt.Dimension(174, 35));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Jenis Buku");

        jenis.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ensiklopedia", "Novel", "Komik", "Biografi", "Dongeng", "Karya Ilmiah" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Judul Buku");

        judul.setBackground(new java.awt.Color(204, 204, 204));
        judul.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        judul.setPreferredSize(new java.awt.Dimension(174, 35));
        judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judulActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Tanggal Peminjaman (YYYY-MM-DD)");

        tgl_pnjm.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tgl_pnjm.setPreferredSize(new java.awt.Dimension(174, 35));
        tgl_pnjm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_pnjmActionPerformed(evt);
            }
        });

        stok.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        stok.setPreferredSize(new java.awt.Dimension(174, 35));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Stok");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setText("Tanggal Kembali (YYYY-MM-DD)");

        tgl_kmbl.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tgl_kmbl.setPreferredSize(new java.awt.Dimension(174, 35));
        tgl_kmbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_kmblActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout data_bukuLayout = new javax.swing.GroupLayout(data_buku);
        data_buku.setLayout(data_bukuLayout);
        data_bukuLayout.setHorizontalGroup(
            data_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_bukuLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(id_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(data_bukuLayout.createSequentialGroup()
                .addGroup(data_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kode_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgl_pnjm, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgl_kmbl, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        data_bukuLayout.setVerticalGroup(
            data_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_bukuLayout.createSequentialGroup()
                .addGroup(data_bukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(id_buku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kode_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tgl_pnjm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tgl_kmbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(data_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 460, 530));

        data_murid.setBackground(new java.awt.Color(255, 255, 255));
        data_murid.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Murid"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("NIM");

        nis.setBackground(new java.awt.Color(204, 204, 204));
        nis.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        nis.setPreferredSize(new java.awt.Dimension(174, 35));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Nama");

        nama.setBackground(new java.awt.Color(204, 204, 204));
        nama.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        nama.setPreferredSize(new java.awt.Dimension(174, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Code");

        kode_siswa.setBackground(new java.awt.Color(204, 204, 204));
        kode_siswa.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        kode_siswa.setPreferredSize(new java.awt.Dimension(174, 35));

        id_murid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_muridActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout data_muridLayout = new javax.swing.GroupLayout(data_murid);
        data_murid.setLayout(data_muridLayout);
        data_muridLayout.setHorizontalGroup(
            data_muridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_muridLayout.createSequentialGroup()
                .addGroup(data_muridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nis, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(data_muridLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63)
                        .addComponent(id_murid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(kode_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        data_muridLayout.setVerticalGroup(
            data_muridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_muridLayout.createSequentialGroup()
                .addGroup(data_muridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_murid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(kode_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(data_murid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 460, -1));

        tbl_murid.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tbl_murid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Jurusan"
            }
        ));
        tbl_murid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_muridMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_murid);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 470, 290));

        cari_buku.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cari_buku.setToolTipText("Cari Buku");
        cari_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_bukuActionPerformed(evt);
            }
        });
        cari_buku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cari_bukuKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cari_bukuKeyTyped(evt);
            }
        });
        jPanel1.add(cari_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 950, 40));

        cari_murid.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cari_murid.setToolTipText("Cari Murid");
        cari_murid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cari_muridKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cari_muridKeyTyped(evt);
            }
        });
        jPanel1.add(cari_murid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 950, 40));

        header.setBackground(new java.awt.Color(15, 4, 76));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        close.setForeground(new java.awt.Color(255, 0, 51));
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        header.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 30, 50));

        jLabel12.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ADD PEMINJAMAN");
        header.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 980, 45));

        simpan.setBackground(new java.awt.Color(74, 176, 12));
        simpan.setForeground(new java.awt.Color(240, 240, 240));
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });
        simpan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/simpan.png"))); // NOI18N
        simpan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SIMPAN");
        simpan.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jPanel1.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 920, 210, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1030, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        
    }//GEN-LAST:event_closeDialog

    private void tbl_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bukuMouseClicked
        // TODO add your handling code here:
        clicktbl_buku();
    }//GEN-LAST:event_tbl_bukuMouseClicked

    private void tbl_muridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_muridMouseClicked
        // TODO add your handling code here:
        clicktbl_murid();
    }//GEN-LAST:event_tbl_muridMouseClicked

    private void judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judulActionPerformed

    private void cari_muridKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cari_muridKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            search_murid();
        }
    }//GEN-LAST:event_cari_muridKeyPressed

    private void cari_muridKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cari_muridKeyTyped
        // TODO add your handling code here:
        search_murid();
    }//GEN-LAST:event_cari_muridKeyTyped

    private void cari_bukuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cari_bukuKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            search_book();
        }
    }//GEN-LAST:event_cari_bukuKeyPressed

    private void cari_bukuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cari_bukuKeyTyped
        // TODO add your handling code here:
        search_book();
    }//GEN-LAST:event_cari_bukuKeyTyped

    private void id_muridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_muridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_muridActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void cari_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_bukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cari_bukuActionPerformed

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisActionPerformed

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
    save();
    }//GEN-LAST:event_simpanMouseClicked

    private void tgl_kmblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_kmblActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tgl_kmblActionPerformed

    private void tgl_pnjmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_pnjmActionPerformed
        // TODO add your handling code here:
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd") ;
        tgl_pnjm.setText(""+kal.format(sekarang));
    }//GEN-LAST:event_tgl_pnjmActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                add_transaksi dialog = new add_transaksi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        
        
    }
    
private void tampil_buku() {
        Object []baris = {"ID", "Kode Buku", "Judul Buku", "Stok"};
        tbl1 = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbl_buku.setModel(tbl1);
        
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT * FROM buku ORDER BY id_buku ASC";
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {
                String id = rs.getString("id_buku");
                String kode = rs.getString("kode");
                String judul = rs.getString("judul");
                String stok = rs.getString("stok");
                
                String[] data = {id, kode, judul, stok};
                tbl1.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan DATA!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            this.setVisible(false);
        }
    }

private void clicktbl_buku() {
        int baris = tbl_buku.getSelectedRow();
        
        id_buku.setText((String)tbl1.getValueAt(baris, 0));
        kode_buku.setText((String)tbl1.getValueAt(baris, 1));
        judul.setText((String)tbl1.getValueAt(baris, 2));
       
        
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT * FROM buku WHERE kode = '"+(String)tbl1.getValueAt(baris, 0)+"'";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet rs = stat.executeQuery(sql);
            
            if (rs.next()) {
                jenis.setSelectedIndex(rs.getInt("jenis")-1);
            }
            
        } catch (Exception e) {}
    }

private void search_book() {
        String query = cari_buku.getText();
        
        Object []baris = {"ID", "Kode Buku", "Judul Buku", "Stok"};
        tbl1 = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbl_buku.setModel(tbl1);
        
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT * FROM buku WHERE BINARY "
                    + "kode LIKE '%"+query+"%' "
                    + "OR judul LIKE '%"+query+"%' "
                    + "ORDER BY id_buku ASC";
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet hasil = stmt.executeQuery(sql);
            
            while (hasil.next()) {
                String kode = hasil.getString("kode");
                String judul = hasil.getString("judul");
                String stok = hasil.getString("stok");
                
                String[] data = {kode, judul, stok};
                tbl1.addRow(data);
                lebarKolombk();
            }
        } catch (Exception e) {}
    }

private void tampil_murid() {
        Object []baris = {"ID", "NIS", "Nama", "Code"};
        tbl2 = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbl_murid.setModel(tbl2);
        
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT * FROM siswa ORDER BY id_siswa ASC";
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {
                String id = rs.getString("id_siswa");
                String nis = rs.getString("nis");
                String nama = rs.getString("nama");
                String code = rs.getString("kode");
                
                
                String[] data = {id, nis, nama, code};
                tbl2.addRow(data);
                lebarKolommrd();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan DATA!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            this.setVisible(false);
        }
    }

 private void clicktbl_murid() {
        int baris = tbl_murid.getSelectedRow();
        
        id_murid.setText((String)tbl2.getValueAt(baris, 0));
        nis.setText((String)tbl2.getValueAt(baris, 1));
        nama.setText((String)tbl2.getValueAt(baris, 2));
        kode_siswa.setText((String)tbl2.getValueAt(baris, 3));
        
    }
    
   private void search_murid() {
        String query = cari_murid.getText();
        
        Object []baris = {"ID","NIS", "Nama", "Code"};
        tbl2 = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbl_murid.setModel(tbl2);
        
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT * FROM siswa WHERE BINARY "
                    + "kode LIKE '%"+query+"%' "
                    + "OR nama LIKE '%"+query+"%' "
                    + "OR nis LIKE '%"+query+"%' "
                    + "ORDER BY id_siswa ASC";
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet hasil = stmt.executeQuery(sql);
            
            while (hasil.next()) {
                String id = hasil.getString("id_siswa");
                String nis = hasil.getString("nis");
                String nama = hasil.getString("nama");
                String code = hasil.getString("kode");
                
                String[] data = {id, nis, nama, code};
                tbl2.addRow(data);
                lebarKolommrd();
            }
        } catch (Exception e) {}
    }
   
    private void save() {
        String id, getidsiswa, getidbuku, gettanggal, gettanggalkmbl, getstok;
        
        getidsiswa = id_murid.getText();
        getidbuku = id_buku.getText();
        gettanggal = tgl_pnjm.getText();
        gettanggalkmbl = tgl_kmbl.getText();
        getstok = stok.getText();
       
        if (empty(getidsiswa) || empty(getidbuku) || empty(gettanggal)) {
           JOptionPane.showMessageDialog(null, "Data yang Anda masukkan belum lengkap!", "Peringatan!", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Connection con = new database.connection().configDB();
                String get = "SELECT * FROM pinjam WHERE id_siswa = '"+getidsiswa+"' AND id_buku = '"+getidbuku+"'";
                java.sql.Statement st = con.createStatement();
                java.sql.ResultSet hasil = st.executeQuery(get);
                
                if (hasil.next()) {
                   JOptionPane.showMessageDialog(null, "Data seperti ini sudah pernah Anda masukkan sebelumnya.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                } else {
                    try {
                        String sql = "INSERT INTO pinjam VALUES (null, ?, ?, ?, ?, ?)";
                        java.sql.PreparedStatement stat = (PreparedStatement)con.prepareStatement(sql);
                        stat.setString(1, getidsiswa);
                        stat.setString(2, getidbuku);
                        stat.setString(3, gettanggal);
                        stat.setString(4, gettanggalkmbl);
                        stat.setString(5, getstok);
                        stat.executeUpdate();

                        this.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Data Peminjaman Berhasil Ditambahkan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Data Peminjaman Tidak Berhasil ", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                   }
                }
            } catch (Exception e) {}
        }
    }
    
private void thisdate() {
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd") ;
        tgl_pnjm.setText(""+kal.format(sekarang));
    }
 
 
    private static boolean empty(final String s) {
        return s == null || s.trim().isEmpty();
    }
    
    public void lebarKolommrd(){ 
        TableColumn column;
        tbl_murid.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tbl_murid.getColumnModel().getColumn(0); 
        column.setPreferredWidth(50);
        column = tbl_murid.getColumnModel().getColumn(1); 
        column.setPreferredWidth(70); 
        column = tbl_murid.getColumnModel().getColumn(2); 
        column.setPreferredWidth(220); 
        column = tbl_murid.getColumnModel().getColumn(3); 
        column.setPreferredWidth(124);
    }
    
    public void lebarKolombk(){ 
        TableColumn column;
        tbl_buku.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tbl_buku.getColumnModel().getColumn(0); 
        column.setPreferredWidth(50);
        column = tbl_buku.getColumnModel().getColumn(1); 
        column.setPreferredWidth(70); 
        column = tbl_buku.getColumnModel().getColumn(2); 
        column.setPreferredWidth(290); 
        column = tbl_buku.getColumnModel().getColumn(3); 
        column.setPreferredWidth(54);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cari_buku;
    private javax.swing.JTextField cari_murid;
    private javax.swing.JLabel close;
    private javax.swing.JPanel data_buku;
    private javax.swing.JPanel data_murid;
    private javax.swing.JPanel header;
    private javax.swing.JTextField id_buku;
    private javax.swing.JTextField id_murid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JTextField judul;
    private javax.swing.JTextField kode_buku;
    private javax.swing.JTextField kode_siswa;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nis;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel simpan;
    private javax.swing.JTextField stok;
    private javax.swing.JTable tbl_buku;
    private javax.swing.JTable tbl_murid;
    private javax.swing.JTextField tgl_kmbl;
    private javax.swing.JTextField tgl_pnjm;
    // End of variables declaration//GEN-END:variables

}
