/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pages;

import java.awt.Point;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author IBRAR
 */
public class add_siswa extends javax.swing.JFrame {

    private static Point point = new Point();
    
  
    
    /**
     * Creates new form add_buku
     */
    public add_siswa() {
        setSize(1200, 550);
        setResizable(false);
        setLocationRelativeTo(null);
        this.setUndecorated(true);
        
        initComponents();
        thisdate();
        
        no_nis.setEnabled(false);
    }

   String cmb_id;
   String id_siswa;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        simpan = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nama_siswa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tgl_lhr = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tpt_lhr = new javax.swing.JTextField();
        no_nis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jenis_jurusan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tgl_msk = new javax.swing.JTextField();
        barcode = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        body.setPreferredSize(new java.awt.Dimension(1153, 845));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(15, 4, 76));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        close.setForeground(new java.awt.Color(255, 0, 51));
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        header.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, 50));

        jLabel12.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ADD SISWA");
        header.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        body.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1350, 45));

        sidebar.setBackground(new java.awt.Color(15, 4, 76));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/20220330_235930 1.png"))); // NOI18N
        sidebar.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 80, -1, -1));

        body.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 600));

        simpan.setBackground(new java.awt.Color(74, 176, 12));
        simpan.setForeground(new java.awt.Color(240, 240, 240));
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });
        simpan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/simpan.png"))); // NOI18N
        simpan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SIMPAN");
        simpan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        body.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 390, 210, 60));

        nama_siswa.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        nama_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_siswaActionPerformed(evt);
            }
        });
        body.add(nama_siswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 330, 40));

        jLabel2.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel2.setText("Nama");
        body.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel4.setText("Tanggal Masuk(YYYY-MM-DD)");
        body.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel7.setText("Tanggal Lahir (YYYY-MM-DD)");
        body.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, -1, -1));

        tgl_lhr.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        body.add(tgl_lhr, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 330, 40));

        jLabel10.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel10.setText("Code");
        body.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        tpt_lhr.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        tpt_lhr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpt_lhrActionPerformed(evt);
            }
        });
        body.add(tpt_lhr, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 330, 40));

        no_nis.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        body.add(no_nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 330, 40));

        jLabel5.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel5.setText("NIS");
        body.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        jenis_jurusan.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jenis_jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknik Komputer dan Jaringan", "Teknik Kendaraan Ringan Otomotif", "Teknik dan Bisnis Sepeda Motor", "Otomatisasi dan Tata Kelola Perkantoran", "Akuntansi dan Keuangan Lembaga", "Bisnis Daring dan Pemasaran" }));
        jenis_jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenis_jurusanActionPerformed(evt);
            }
        });
        body.add(jenis_jurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 330, 40));

        jLabel1.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("?");
        jLabel1.setToolTipText("NIS akan terisi otomatis");
        body.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 20, 30));

        jLabel6.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel6.setText("Tempat lahir");
        body.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, -1, -1));

        tgl_msk.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        tgl_msk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_mskActionPerformed(evt);
            }
        });
        body.add(tgl_msk, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 330, 40));

        barcode.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        body.add(barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 330, 40));

        jLabel11.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabel11.setText("Jurusan");
        body.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void tgl_mskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_mskActionPerformed
        // TODO add your handling code here:

        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd") ;
        tgl_msk.setText(""+kal.format(sekarang));

    }//GEN-LAST:event_tgl_mskActionPerformed

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked

        String getnis, getnama, gettanggalmsk, gettgllahir, gettempat, getjenis, getcode;

        getnis = no_nis.getText();
        getnama = nama_siswa.getText();
        gettempat = tpt_lhr.getText();
        gettgllahir = tgl_lhr.getText();
        getjenis = (String)jenis_jurusan.getSelectedItem();
        gettanggalmsk = tgl_msk.getText();
        getcode = barcode.getText();
        

        if (empty(getnis) || empty(getnama) || empty(gettanggalmsk) || empty(getcode) || empty(getjenis) || empty(gettgllahir) || empty(gettempat)) {
            JOptionPane.showMessageDialog(null, "Data yang Anda masukkan belum lengkap!", "Peringatan!", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Connection con = new database.connection().configDB();
                String get = "SELECT * FROM siswa WHERE nis = '"+getnis+"'";
                java.sql.Statement st = con.createStatement();
                java.sql.ResultSet hasil = st.executeQuery(get);

                if (hasil.next()) {
                    JOptionPane.showMessageDialog(null, "NIS tidak boleh ada yang sama.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                } else {
                    try {
                        String sql = "INSERT INTO siswa VALUES (null, ?, ?, ?, ?, ?, ?,?)";
                        java.sql.PreparedStatement stat = (PreparedStatement)con.prepareStatement(sql);
                        stat.setString(1, getnis);
                        stat.setString(2, getnama);
                        stat.setString(3, gettempat);
                        stat.setString(4, gettgllahir);
                        stat.setString(5, getjenis);
                        stat.setString(6, gettanggalmsk);
                        stat.setString(7, getcode);

                        stat.executeUpdate();

                        this.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Data Siswa Berhasil Ditambahkan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {                    
                        JOptionPane.showMessageDialog(null, "Data Siswa Gagal Disimpan", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (Exception e) {}
        }
    }//GEN-LAST:event_simpanMouseClicked

    private void nama_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_siswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_siswaActionPerformed

    private void tpt_lhrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpt_lhrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpt_lhrActionPerformed

    private void jenis_jurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenis_jurusanActionPerformed
        // TODO add your handling code here:
        kode();
    }//GEN-LAST:event_jenis_jurusanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_siswa().setVisible(true);
            }
        });
    }
    
      
        
        private void thisdate() {
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd") ;
        tgl_msk.setText(""+kal.format(sekarang));
    }
        
        private static boolean empty(final String s) {
        return s == null || s.trim().isEmpty();
    }
public void kode(){
         cmb_id = (String) jenis_jurusan.getSelectedItem();
    if ("Teknik Komputer dan Jaringan".equals(cmb_id)) {
     id_siswa= "TKJ"+getRandom();
      } else if ("Teknik Kendaraan Ringan Otomotif".equals(cmb_id)) {
     id_siswa = "TKR"+getRandom();
      } else if ("Teknik dan Bisnis Sepeda Motor".equals(cmb_id)) {
     id_siswa = "TBSM"+getRandom();
      } else if("Otomatisasi dan Tata Kelola Perkantoran".equals(cmb_id)){
       id_siswa = "OTP"+getRandom();
      }else if("Akuntansi dan Keuangan Lembaga".equals(cmb_id)){
          id_siswa = "AKL"+getRandom();
      } else if("Bisnis Daring dan Pemasaran".equals(cmb_id)){
          id_siswa = "BDP"+getRandom();
      } 
    no_nis.setText(id_siswa);
    }
           
           private String getRandom() {
        for (int length = 0; length < 3; length++) {
            Character character = chars[random.nextInt(chars.length)];
            stringBuilder.append(character);
        }
        output = stringBuilder.toString();
        stringBuilder.delete(0, 6);
        return output;
    }
           
           private char[] chars = "1234567890".toCharArray();
    private StringBuilder stringBuilder = new StringBuilder();
    private Random random = new Random();
    private String output;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barcode;
    private javax.swing.JPanel body;
    private javax.swing.JLabel close;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jenis_jurusan;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField nama_siswa;
    private javax.swing.JTextField no_nis;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel simpan;
    private javax.swing.JTextField tgl_lhr;
    private javax.swing.JTextField tgl_msk;
    private javax.swing.JTextField tpt_lhr;
    // End of variables declaration//GEN-END:variables
}
