/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pages;

import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import master.buku;

/**
 *
 * @author IBRAR
 */
public class data_kembali extends javax.swing.JFrame {

    private static Point point = new Point();
    
       
    
    /**
     * Creates new form add_buku
     */
    public data_kembali() {
        setSize(1300, 800);
        setResizable(false);
        setLocationRelativeTo(null);
        this.setUndecorated(true);
        
        initComponents();
        tampil_data();
        lebarKolom();
    }

    DefaultTableModel tbl2 = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        result_siswa = new javax.swing.JLabel();
        search_transaksi = new placeholder.search();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_kembali = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        body.setPreferredSize(new java.awt.Dimension(1153, 845));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(15, 4, 76));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        close.setForeground(new java.awt.Color(255, 0, 51));
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        header.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 40, 50));

        jLabel12.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DATA KEMBALI");
        header.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        body.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 1470, 45));

        sidebar.setBackground(new java.awt.Color(15, 4, 76));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LIBRARY.png"))); // NOI18N
        sidebar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 130, 570));

        body.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 790));

        result_siswa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        result_siswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        body.add(result_siswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 680, 40));

        search_transaksi.setToolTipText("Cari Data");
        search_transaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        search_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_transaksiActionPerformed(evt);
            }
        });
        search_transaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_transaksiKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_transaksiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_transaksiKeyTyped(evt);
            }
        });
        body.add(search_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, 230, 40));

        tb_kembali.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tb_kembali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title1", "Title2", "Title3", "Title4"
            }
        ));
        jScrollPane1.setViewportView(tb_kembali);

        body.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 1010, 610));

        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void search_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_transaksiActionPerformed

    private void search_transaksiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_transaksiKeyPressed
        //         TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            search_transaksi();
        }
    }//GEN-LAST:event_search_transaksiKeyPressed

    private void search_transaksiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_transaksiKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_search_transaksiKeyReleased

    private void search_transaksiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_transaksiKeyTyped
        // TODO add your handling code here:
        search_transaksi();
    }//GEN-LAST:event_search_transaksiKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_kembali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_kembali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_kembali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_kembali.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_kembali().setVisible(true);
            }
        });
    }
    
private void tampil_data() {
        Object []baris = {"ID", "NIS", "Nama", "Jurusan", "Kode Buku", "Judul Buku", "Jenis Buku", "Tanggal Pinjam", "Tanggal Kembali", "Stok", "Denda"};
        tbl2 = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tb_kembali.setModel(tbl2);
        try {
            Connection con = new database.connection().configDB();
            String sql = "SELECT siswa.*, buku.*, kembali.* FROM siswa, buku, kembali WHERE siswa.id_siswa = kembali.id_siswa AND buku.id_buku = kembali.id_buku ORDER BY id_kembali ASC";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            
            while (hasil.next()) {
                String idpinjam = hasil.getString("kembali.id_kembali");
                String nis = hasil.getString("siswa.nis");
                String nama = hasil.getString("siswa.nama");
                String jurusan = hasil.getString("siswa.jurusan");
                String kode = hasil.getString("buku.kode");
                String judul = hasil.getString("buku.judul");
                String jenis = hasil.getString("buku.jenis");
                String tanggal_pnjm = hasil.getString("kembali.tgl_pinjam");
                String tanggal_kmbl = hasil.getString("kembali.tgl_kembali");
                String stok = hasil.getString("kembali.stok");
                String denda = hasil.getString("kembali.denda");
                
                if (hasil.getString("jenis").equals("1")) {
                    jenis = "Ensiklopedia";
                } else if (hasil.getString("jenis").equals("2")) {
                    jenis = "Novel";
                } else if (hasil.getString("jenis").equals("3")) {
                    jenis = "Komik";
                } else if (hasil.getString("jenis").equals("4")) {
                    jenis = "Biografi";
                } else if (hasil.getString("jenis").equals("5")) {
                    jenis = "Dongeng";
                } else if (hasil.getString("jenis").equals("6")) {
                    jenis = "Karya Ilmiah";
                }
                
                String[] data = {idpinjam, nis, nama, jurusan, kode, judul, jenis, tanggal_pnjm, tanggal_kmbl, stok, denda};
                tbl2.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan DATA!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
            dispose();
        }
    }

public void lebarKolom(){ 
        TableColumn column;
        tb_kembali.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tb_kembali.getColumnModel().getColumn(0); 
        column.setPreferredWidth(50);
        column = tb_kembali.getColumnModel().getColumn(1); 
        column.setPreferredWidth(70); 
        column = tb_kembali.getColumnModel().getColumn(2); 
        column.setPreferredWidth(140); 
        column = tb_kembali.getColumnModel().getColumn(3); 
        column.setPreferredWidth(130);
        column = tb_kembali.getColumnModel().getColumn(4); 
        column.setPreferredWidth(80);
        column = tb_kembali.getColumnModel().getColumn(5); 
        column.setPreferredWidth(110);
        column = tb_kembali.getColumnModel().getColumn(6); 
        column.setPreferredWidth(120);
        column = tb_kembali.getColumnModel().getColumn(7); 
        column.setPreferredWidth(100);
        column = tb_kembali.getColumnModel().getColumn(8); 
        column.setPreferredWidth(100);
        column = tb_kembali.getColumnModel().getColumn(9); 
        column.setPreferredWidth(50);
        column = tb_kembali.getColumnModel().getColumn(10); 
        column.setPreferredWidth(54);
    }

private void search_transaksi() {
        String query = search_transaksi.getText();
        
       Object []baris = {"ID", "NIS", "Nama", "Code", "Kode Buku", "Judul Buku", "Jenis Buku", "Tanggal Pinjam", "Tanggal Kembali", "Stok", "Denda"};
        tbl2 = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tb_kembali.setModel(tbl2);
        
        try {
            Connection con = new database.connection().configDB();
            String sql ="SELECT * FROM kembali JOIN buku ON kembali.id_buku = buku.id_buku JOIN siswa ON siswa.id_siswa = kembali.id_siswa WHERE CONCAT(id_kembali, siswa.nis, siswa.nama, siswa.kode, siswa.jurusan, buku.kode, buku.judul, buku.jenis, kembali.tgl_pinjam, kembali.tgl_kembali) LIKE '%"+query+"%'";
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet hasil = stmt.executeQuery(sql);
            
            while (hasil.next()) {
                String idpinjam = hasil.getString("kembali.id_kembali");
                String nis = hasil.getString("siswa.nis");
                String nama = hasil.getString("siswa.nama");
                String code = hasil.getString("siswa.kode");
                String kode = hasil.getString("buku.kode");
                String judul = hasil.getString("buku.judul");
                String jenis = hasil.getString("buku.jenis");
                String tanggal_pnjm = hasil.getString("kembali.tgl_pinjam");
                String tanggal_kmbl = hasil.getString("kembali.tgl_kembali");
                String stok = hasil.getString("kembali.stok");
                String denda = hasil.getString("kembali.denda");
             
                String[] data = {idpinjam, nis, nama, code, kode, judul, jenis, tanggal_pnjm, tanggal_kmbl, stok, denda};
                tbl2.addRow(data);
                lebarKolom();
            }
            
            if (!query.equals("")) {
                result_siswa.setText("Hasil pencarian dari: '"+query+"'");
            } else {
                result_siswa.setText("");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JLabel close;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel result_siswa;
    private javax.swing.JTextField search_transaksi;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTable tb_kembali;
    // End of variables declaration//GEN-END:variables
}
